### ISSUE TITLE
Cmake的问题如何解决啊（小弟没做过C++等开发）

### ISSUE THREAD

**Issue by ray0807** [venshine/AppUninstall#2]
![1](https://cloud.githubusercontent.com/assets/7233544/17009981/76ebdbda-4f32-11e6-92a6-037935acdeab.jpg)

**Comment by ray0807** [comment]
![1](https://cloud.githubusercontent.com/assets/7233544/17013221/973039fa-4f4f-11e6-84a3-28ff2ad2ad57.jpg)
![2](https://cloud.githubusercontent.com/assets/7233544/17013230/ab19456a-4f4f-11e6-8094-33e12775c11b.jpg)
![3](https://cloud.githubusercontent.com/assets/7233544/17013237/b9788a12-4f4f-11e6-95c7-60c4c660c5f6.jpg)

fork()的pid  不等于0  所以一直都不会走到监听的逻辑中，这个是怎么回事呀？

**Comment by venshine** [comment]
确认fork后pid不等于0？提供一下系统版本和手机型号。
http://linux.die.net/man/2/fork

**Comment by ray0807** [comment]
我试了很多次，没有一次等于0的，galaxy3 ，5.1.1版本（自己刷的rom，有影响么？）
子进程fork()后  pid应该=0  但是不知道是不是我的手机问题，pid一直都是大于0的

**Comment by ray0807** [comment]
@venshine

**Comment by venshine** [comment]
写一个Demo，JNI调用C方法只fork进程并打印，看是否结果还是你说的那样。

**Comment by ray0807** [comment]
@venshine  我测试过了  我如果使用fork()得到的pid每次都>0，如果使用getpid()是一个固定值
![1](https://cloud.githubusercontent.com/assets/7233544/17045791/45499b3a-4fff-11e6-800a-5782b72b0382.jpg)
我已经凌乱了 我都怀疑我的手机是不是linux系统的
等下我再用虚拟机试试

**Comment by venshine** [comment]
@ray0807 你的问题很特别，虚拟机结果应该没问题，我看你的代码fork两次，你只fork一次打印一下看看结果是否还有问题。

**Comment by happyKen** [comment]
小米系列好像不兼容吧？有解决方法吗？

**Comment by venshine** [comment]
@happyKen 参考[Android进程保活](http://mp.weixin.qq.com/s?src=3&timestamp=1470993425&ver=1&signature=V1faUU3FI*sBdSMLlormX--tovDsktPhPGaS*Vqptg8hwrYcSjFDhmCKldFI59DU*4JvsKou5xB5I*RD9qj2qEhlWFUsDEuo2XaXLyb97pVGIk81fzxz2Clyeczlks1hLoWqc5qv4LZwxMwRY*sbbgelWZz6nNZIiA3olctzVi8=)

**Comment by happyKen** [comment]
能否提供一下com.wx.android.common.util.AppUtils这个类？你的github上没有提供

**Comment by happyKen** [comment]
还有这个com.wx.android.common.util.PackageUtils;？

**Comment by venshine** [comment]
@happyKen 参考[https://github.com/venshine/AndroidCommon](https://github.com/venshine/AndroidCommon)
